# -*- coding: utf-8 -*-
"""Download_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yRaMZdDc1QNA8DXDZyaRRvJF6oCkL5ws
"""

# Install the ucimlrepo library
!pip install ucimlrepo

import pandas as pd
import numpy as np

from ucimlrepo import fetch_ucirepo, list_available_datasets

# Check available datasets
list_available_datasets()

# Example: Fetch Heart Disease dataset
heart_disease = fetch_ucirepo(id=45)

# Access features and targets
X = heart_disease.data.features
y = heart_disease.data.targets

print(X.head())
print(y.head())

print("\nDataset Information:")
print(heart_disease.metadata)

print("\nFeature Information:")
print(X.info())

print("\nMissing Values:")
print(X.isnull().sum())

print("\nTarget Distribution:")
print(y.value_counts())

# Convert target into binary classification
y_binary = (y["num"] > 0).astype(int)

# Handle missing values
X_clean = X.copy()
X_clean = X_clean.fillna(X_clean.median(numeric_only=True))

print("Missing values after cleaning:")
print(X_clean.isnull().sum())

print("\nBinary target distribution:")
print(y_binary.value_counts())

